apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: img-classifier-hub
  namespace: openfaas-fn
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: img-classifier-hub
  minReplicas: 1
  maxReplicas: 30
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 90
  - type: Pods
    pods:
      metric: 
        name: http_requests_per_second
      target:
        type: AverageValue
        averageValue: 4
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 30
      policies:
      - type: Percent
        value: 100
        periodSeconds: 30
