# -*- mode: ruby -*-
# vi: set ft=ruby :

require_relative 'environment.rb'
include Variables

$headnode = <<-HEADNODE
curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=$1 INSTALL_K3S_EXEC="--advertise-address 192.168.50.99 \
        --flannel-iface nebula \
        --kube-apiserver-arg "enable-admission-plugins=PodNodeSelector"" sh -
HEADNODE

$install = <<-SCRIPT
export K3S_RESOLV_CONF=/run/systemd/resolve/resolv.conf
echo "export K3S_RESOLV_CONF=/run/systemd/resolve/resolv.conf" >> /home/vagrant/.bashrc
echo "vm.max_map_count=262144" >> vm.conf
sudo mv vm.conf /etc/sysctl.d/
sleep 10
curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=$1 K3S_URL=https://192.168.50.99:6443 \
K3S_TOKEN=$(cat /vagrant/node-token) \
INSTALL_K3S_EXEC="--flannel-iface nebula" sh -
SCRIPT

ENV['VAGRANT_NO_PARALLEL'] = 'yes'
Vagrant.configure("2") do |config|
  config.vm.provider "libvirt"
  config.hostmanager.enabled = false
  config.hostmanager.manage_host = false
  config.hostmanager.manage_guest = true
  config.hostmanager.ignore_private_ip = true
  config.hostmanager.include_offline = true

  config.vm.define "lighthouse" do |lighthouse|
    lighthouse.vm.box = $VMIMAGE
    lighthouse.vm.hostname = "lighthouse"
    lighthouse.vm.network "public_network",
      bridge: $BRIDGE_BENCH, dev: $BRIDGE_BENCH, use_dhcp_assigned_default_route: true
    lighthouse.vm.synced_folder "../..", "/vagrant", type: "nfs", nfs_udp: false
    lighthouse.vm.provider "libvirt" do |v1|
      v1.memory = "512"
      v1.cpus = "1"
    end
    lighthouse.vm.provision :shell,
      inline: "echo `ip addr sh eth1 | grep 'inet ' | awk '{print substr($2, 1, length($2)-3)}'` > /vagrant/lighthouse.ip"
  end

  config.vm.define "headnode", primary: true do |headnode|
    headnode.vm.box = $VMIMAGE
    headnode.vm.hostname = "headnode"
    #This interface is linked directly to the test machine:
    headnode.vm.network "public_network",
      bridge: $BRIDGE_BENCH, dev: $BRIDGE_BENCH, ip: $BRIDGE_IP
    headnode.vm.synced_folder "../..", "/vagrant", type: "nfs", nfs_udp: false
    headnode.vm.provider "libvirt" do |v3|
      v3.memory = "#{$VMMEM}"
      v3.cpus = "#{$VMCPU}"
    end

    headnode.vm.provision :shell, 
      inline: "echo 'set bell-style none' >> /etc/inputrc \
        && echo 'set visualbell' >> /home/vagrant/.vimrc"
    headnode.vm.provision :shell, 
      inline: "DEBIAN_FRONTEND=noninteractive apt-get update"
    headnode.vm.provision :shell, inline: "chmod +x /vagrant/deployment_toolkit/vm/vm_repocfg.sh"
    headnode.vm.provision :shell, inline: "/vagrant/deployment_toolkit/vm/vm_repocfg.sh"
    #Install K3s server and move the authentication token to an accessible location for the other machines to read
    headnode.vm.provision "shell",
      run: "always", inline: $headnode, args: $K3SVERSION
    headnode.vm.provision :shell,
      inline: "cp /var/lib/rancher/k3s/server/node-token /vagrant/node-token"
    headnode.vm.provision :shell, inline: "chmod 777 /vagrant/node-token"
  end

  (1..$NODE_COUNT).each do |i|
    config.vm.define "worker#{i}" do |worker|
      worker.vm.box = $VMIMAGE
      worker.vm.hostname = "worker#{i}"
      worker.vm.network "public_network",
        bridge: $BRIDGE_BENCH, dev: $BRIDGE_BENCH, use_dhcp_assigned_default_route: true
      worker.vm.synced_folder "../..", "/vagrant", type: "nfs", nfs_udp: false
      worker.vm.provider "libvirt" do |v1|
        v1.memory = "#{$VMMEM}"
        v1.cpus = "#{$VMCPU}"
      end

      worker.vm.provision :shell,
        inline: "echo 'set bell-style none' >> /etc/inputrc \
          && echo 'set visualbell' >> /home/vagrant/.vimrc"
      worker.vm.provision :shell,
        inline: "DEBIAN_FRONTEND=noninteractive apt-get update \
          && apt-get install docker.io build-essential -y"
      worker.vm.provision :shell, inline: "/vagrant/deployment_toolkit/vm/vm_repocfg.sh"
      worker.vm.provision :shell, inline: $install, args: $K3SVERSION
    end
  end

  config.vm.provision :shell,
    inline: "echo $(cat /vagrant/lighthouse.ip) lighthouse | tee -a /etc/hosts"
  config.vm.provision :shell,
    path: "../nebula/nebula.sh", args: $NEBULAVERSION
  unless 0 == $TOTAL_DELAY
    config.vm.provision :shell, inline: "tc qdisc add dev eth1 root netem delay #{$TOTAL_DELAY}ms \"#{$DELAY_VAR}\"ms distribution normal loss \"#{$PACKET_LOSS}\"%"
  end
end
