apiVersion: v1
kind: Namespace
metadata:
  name: openfaas
  annotations:
    scheduler.alpha.kubernetes.io/node-selector: env=ingress
    linkerd.io/inject: enabled
    config.linkerd.io/skip-inbound-ports: "4222"
    config.linkerd.io/skip-outbound-ports: "4222"
  labels:
    role: openfaas-system
    access: openfaas-system
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: openfaas-fn
  annotations:
    scheduler.alpha.kubernetes.io/node-selector: node-role.kubernetes.io/worker=worker
    linkerd.io/inject: enabled
    config.linkerd.io/skip-inbound-ports: "4222"
    config.linkerd.io/skip-outbound-ports: "4222"
    prometheus.io.scrape: "true"
    prometheus.io.port: "8081"
  labels:
    istio-injection: enabled
    role: openfaas-fn
